context:
  name: mparray
  version: "0.2.1"
  python_min: "3.13"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 61cb99fb52cfc098a1ab2933e746569678a6c9c081ad1d41d8dc39c83338ab67

build:
  noarch: python
  number: 0
  script: python -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build >=0.10.8,<0.11.0
  run:
    - python >=${{ python_min }}
    - numpy
    - mpmath
    - scipy

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - mparray
      pip_check: true

about:
  homepage: https://github.com/mdhaber/mparray
  summary: Array API-compatible, arbitrary-precision arrays
  license: MIT
  license_file: LICENSE
  repository: https://github.com/mdhaber/mparray

extra:
  recipe-maintainers:
    - mdhaber
